# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "testcluster"
#   createdAt: 2021-11-24T11:00:12.297221306Z
#   expiresAt: 2022-11-24T11:00:00Z
#   id:        addbc9f4-f79c-4517-b639-42d46c2158c5
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2021-11-24T11:00:12.297221306Z"
    init-bundle.stackrox.io/expires-at: "2022-11-24T11:00:00Z"
    init-bundle.stackrox.io/id: addbc9f4-f79c-4517-b639-42d46c2158c5
    init-bundle.stackrox.io/name: testcluster
  creationTimestamp: null
  name: collector-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0DCCAXagAwIBAgIUOOR6+OdUDj3I+ov68eqgsnmVhswwCgYIKoZIzj0EAwIw
    RjEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYD
    VQQFExIzNTA1MjQ1MzUwNTQ1MTk4MDkwHhcNMjExMTI0MTA0MjAwWhcNMjYxMTIz
    MTA0MjAwWjBGMScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
    dHkxGzAZBgNVBAUTEjM1MDUyNDUzNTA1NDUxOTgwOTBZMBMGByqGSM49AgEGCCqG
    SM49AwEHA0IABHZsTg9O0fPl1kygg1ldN9/3hvUW6hUZcd46yORRKtXeNO1yl9cH
    1uKvTWGl9ye3HY8S2SGy0zU1D2DlO3G8lqGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSMJ7MG9bEYJVIiM99LxH85Bm1ieTAK
    BggqhkjOPQQDAgNIADBFAiASzeUv8xt2rCik1cv/SrNIBNh+qzzLNpVI+9xHor/M
    VAIhAL4IG8kuAsAJ2cOQaZXUOmrMUjLTU809ONPiGH4OSQLC
    -----END CERTIFICATE-----
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICnzCCAkagAwIBAgIIZMeNCYNfL2EwCgYIKoZIzj0EAwIwRjEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYDVQQFExIzNTA1MjQ1
    MzUwNTQ1MTk4MDkwHhcNMjExMTI0MTAwMDAwWhcNMjIxMTI0MTEwMDAwWjCBqzEt
    MCsGA1UEChMkYWRkYmM5ZjQtZjc5Yy00NTE3LWI2MzktNDJkNDZjMjE1OGM1MRow
    GAYDVQQLDBFDT0xMRUNUT1JfU0VSVklDRTFAMD4GA1UEAww3Q09MTEVDVE9SX1NF
    UlZJQ0U6IDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEcMBoG
    A1UEBRMTNzI2MTkyNzk5NjE1NjQ4OTU2OTBZMBMGByqGSM49AgEGCCqGSM49AwEH
    A0IABD7YqImvhQVtlLdDq7gSF9OCmGEy6S5TLSvFTY68TcFsjuA7YS+NMu3foWKD
    K7AV7JDLTjwidHAdip9JGPqTl7KjgbcwgbQwDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
    BBTBo9JJ/Oq/skrJ1DLgJh5aaCM5ezAfBgNVHSMEGDAWgBSMJ7MG9bEYJVIiM99L
    xH85Bm1ieTA1BgNVHREELjAsghJjb2xsZWN0b3Iuc3RhY2tyb3iCFmNvbGxlY3Rv
    ci5zdGFja3JveC5zdmMwCgYIKoZIzj0EAwIDRwAwRAIgd8h0PM1NP8ynNXvQDPc4
    WqIb4ZG97DjVRIZB0Slp+m8CIGFU70zHUg+C7woAjWivM7NKKPDpZQp27SXxdNw3
    ROoN
    -----END CERTIFICATE-----
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIE2m3kPQIcjUbaHhYdn+2P1vBsj4ZJP4zz+MOVAv7clMoAoGCCqGSM49
    AwEHoUQDQgAEPtioia+FBW2Ut0OruBIX04KYYTLpLlMtK8VNjrxNwWyO4DthL40y
    7d+hYoMrsBXskMtOPCJ0cB2Kn0kY+pOXsg==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2021-11-24T11:00:12.297221306Z"
    init-bundle.stackrox.io/expires-at: "2022-11-24T11:00:00Z"
    init-bundle.stackrox.io/id: addbc9f4-f79c-4517-b639-42d46c2158c5
    init-bundle.stackrox.io/name: testcluster
  creationTimestamp: null
  name: sensor-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0DCCAXagAwIBAgIUOOR6+OdUDj3I+ov68eqgsnmVhswwCgYIKoZIzj0EAwIw
    RjEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYD
    VQQFExIzNTA1MjQ1MzUwNTQ1MTk4MDkwHhcNMjExMTI0MTA0MjAwWhcNMjYxMTIz
    MTA0MjAwWjBGMScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
    dHkxGzAZBgNVBAUTEjM1MDUyNDUzNTA1NDUxOTgwOTBZMBMGByqGSM49AgEGCCqG
    SM49AwEHA0IABHZsTg9O0fPl1kygg1ldN9/3hvUW6hUZcd46yORRKtXeNO1yl9cH
    1uKvTWGl9ye3HY8S2SGy0zU1D2DlO3G8lqGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSMJ7MG9bEYJVIiM99LxH85Bm1ieTAK
    BggqhkjOPQQDAgNIADBFAiASzeUv8xt2rCik1cv/SrNIBNh+qzzLNpVI+9xHor/M
    VAIhAL4IG8kuAsAJ2cOQaZXUOmrMUjLTU809ONPiGH4OSQLC
    -----END CERTIFICATE-----
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICsTCCAlegAwIBAgIILdkGda3T8g4wCgYIKoZIzj0EAwIwRjEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYDVQQFExIzNTA1MjQ1
    MzUwNTQ1MTk4MDkwHhcNMjExMTI0MTAwMDAwWhcNMjIxMTI0MTEwMDAwWjCBpTEt
    MCsGA1UEChMkYWRkYmM5ZjQtZjc5Yy00NTE3LWI2MzktNDJkNDZjMjE1OGM1MRcw
    FQYDVQQLDA5TRU5TT1JfU0VSVklDRTE9MDsGA1UEAww0U0VOU09SX1NFUlZJQ0U6
    IDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEcMBoGA1UEBRMT
    MzMwMzY3ODkwNDE1MDI1ODE5MDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHv9
    xtRo8rah2/11ZstfaQkWxnSgrBqIVO1ceF029hibd4r9ocm0aDpe9XN4w3uuXTuM
    7YmZhqgwHdCKkRznApmjgc4wgcswDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQG
    CCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTtWr4A
    lWdf9eHyxOK6+JwiJo0EvzAfBgNVHSMEGDAWgBSMJ7MG9bEYJVIiM99LxH85Bm1i
    eTBMBgNVHREERTBDgg9zZW5zb3Iuc3RhY2tyb3iCE3NlbnNvci5zdGFja3JveC5z
    dmOCG3NlbnNvci13ZWJob29rLnN0YWNrcm94LnN2YzAKBggqhkjOPQQDAgNIADBF
    AiAcylaLlhWySKF2aoAqHbk1HMt1voU4k/NBpaJS0N+w0QIhAIVKvaOjPzL85bRY
    NDXUdYnsDviTfacQlRdST81fAALh
    -----END CERTIFICATE-----
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIJoHzBeEu8OL4Btkx0vsFxVWzhOUarqZVS7VX54DDyVPoAoGCCqGSM49
    AwEHoUQDQgAEe/3G1GjytqHb/XVmy19pCRbGdKCsGohU7Vx4XTb2GJt3iv2hybRo
    Ol71c3jDe65dO4ztiZmGqDAd0IqRHOcCmQ==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2021-11-24T11:00:12.297221306Z"
    init-bundle.stackrox.io/expires-at: "2022-11-24T11:00:00Z"
    init-bundle.stackrox.io/id: addbc9f4-f79c-4517-b639-42d46c2158c5
    init-bundle.stackrox.io/name: testcluster
  creationTimestamp: null
  name: admission-control-tls
stringData:
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICwDCCAmagAwIBAgIIG2aMx9Tcv6swCgYIKoZIzj0EAwIwRjEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYDVQQFExIzNTA1MjQ1
    MzUwNTQ1MTk4MDkwHhcNMjExMTI0MTAwMDAwWhcNMjIxMTI0MTEwMDAwWjCBuzEt
    MCsGA1UEChMkYWRkYmM5ZjQtZjc5Yy00NTE3LWI2MzktNDJkNDZjMjE1OGM1MSIw
    IAYDVQQLDBlBRE1JU1NJT05fQ09OVFJPTF9TRVJWSUNFMUgwRgYDVQQDDD9BRE1J
    U1NJT05fQ09OVFJPTF9TRVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0w
    MDAwMDAwMDAwMDAxHDAaBgNVBAUTEzE5NzQ0MjAyNzY1NDYxNTg1MDcwWTATBgcq
    hkjOPQIBBggqhkjOPQMBBwNCAAQ5D52Ww0EK1xTp3Zb+cHbFHUycYfqBiKmKBR5J
    1vWVBoXXiFJPgtR1US7bDOQMgI1PW8wnem+i3N65XPvWmv3Oo4HHMIHEMA4GA1Ud
    DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
    AQH/BAIwADAdBgNVHQ4EFgQU/zXm0kZXk6Hc0lzl9UXOP4URmEQwHwYDVR0jBBgw
    FoAUjCezBvWxGCVSIjPfS8R/OQZtYnkwRQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNv
    bnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94LnN2YzAK
    BggqhkjOPQQDAgNIADBFAiBrfwfHwvEoBFFzdxQDV/Bc1DaTOXOcCOn3LgkK2LvR
    CAIhAOjEBdgIcv0bINrcFnr5AsjKYxbEH0a2gbXpCPx0Unwc
    -----END CERTIFICATE-----
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIHDNH9MTA9FHUA3R94XLtcWZ0qxFGvnKusu0ZQU1BfAKoAoGCCqGSM49
    AwEHoUQDQgAEOQ+dlsNBCtcU6d2W/nB2xR1MnGH6gYipigUeSdb1lQaF14hST4LU
    dVEu2wzkDICNT1vMJ3pvotzeuVz71pr9zg==
    -----END EC PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0DCCAXagAwIBAgIUOOR6+OdUDj3I+ov68eqgsnmVhswwCgYIKoZIzj0EAwIw
    RjEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYD
    VQQFExIzNTA1MjQ1MzUwNTQ1MTk4MDkwHhcNMjExMTI0MTA0MjAwWhcNMjYxMTIz
    MTA0MjAwWjBGMScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
    dHkxGzAZBgNVBAUTEjM1MDUyNDUzNTA1NDUxOTgwOTBZMBMGByqGSM49AgEGCCqG
    SM49AwEHA0IABHZsTg9O0fPl1kygg1ldN9/3hvUW6hUZcd46yORRKtXeNO1yl9cH
    1uKvTWGl9ye3HY8S2SGy0zU1D2DlO3G8lqGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSMJ7MG9bEYJVIiM99LxH85Bm1ieTAK
    BggqhkjOPQQDAgNIADBFAiASzeUv8xt2rCik1cv/SrNIBNh+qzzLNpVI+9xHor/M
    VAIhAL4IG8kuAsAJ2cOQaZXUOmrMUjLTU809ONPiGH4OSQLC
    -----END CERTIFICATE-----
