# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "testcluster"
#   createdAt: 2021-11-25T09:56:33.563752739Z
#   expiresAt: 2022-11-25T09:57:00Z
#   id:        c09bc01d-5c2a-4df7-97c5-e3dd4bfd255a
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2021-11-25T09:56:33.563752739Z"
    init-bundle.stackrox.io/expires-at: "2022-11-25T09:57:00Z"
    init-bundle.stackrox.io/id: c09bc01d-5c2a-4df7-97c5-e3dd4bfd255a
    init-bundle.stackrox.io/name: testcluster
  creationTimestamp: null
  name: collector-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUDqy1Lgt8MmufKg+ldH+RWjOAltQwCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM5MzY2OTk3MjcyNzY5NDg2NjYzMB4XDTIxMTEyNTA5MDgwMFoXDTI2MTEy
    NDA5MDgwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM5MzY2OTk3MjcyNzY5NDg2NjYzMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEkKu/wxEMkOJi07yovyCyJVTB+wGdyQevxZBDzeoZwjI8aM+7
    HUJ83HhnnDUZyD7nA8rqaI/GmawCwsqanckWf6NCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCAenzBYMloC7GdFoELUp2gAvU6i
    MAoGCCqGSM49BAMCA0kAMEYCIQDktvBalsuATtwHj12hQhiYfKFPmwNwRsoKQw/g
    LZaU7AIhAL+GZx/4UEgOWmaXGQe8YBELnTxM1NGqrjCSlmR7GRmw
    -----END CERTIFICATE-----
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICoTCCAkegAwIBAgIIQ1OICbceKqwwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExM5MzY2OTk3
    MjcyNzY5NDg2NjYzMB4XDTIxMTEyNTA4NTcwMFoXDTIyMTEyNTA5NTcwMFowgasx
    LTArBgNVBAoTJGMwOWJjMDFkLTVjMmEtNGRmNy05N2M1LWUzZGQ0YmZkMjU1YTEa
    MBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0UxQDA+BgNVBAMMN0NPTExFQ1RPUl9T
    RVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHDAa
    BgNVBAUTEzQ4NTEzNzA3OTg5MTY0NDY4OTIwWTATBgcqhkjOPQIBBggqhkjOPQMB
    BwNCAATiwy9v9NUDC/ab0IpbDFmIliGWQptLpNp0V6uyiqoEahvmuYcdl+dfHGC6
    8KFhpRDtrk3QYtvhCagSRgUwk+QCo4G3MIG0MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQU4JDf4r0I4T8WfcGMfMN0+Qvp/MAwHwYDVR0jBBgwFoAUIB6fMFgyWgLsZ0Wg
    QtSnaAC9TqIwNQYDVR0RBC4wLIISY29sbGVjdG9yLnN0YWNrcm94ghZjb2xsZWN0
    b3Iuc3RhY2tyb3guc3ZjMAoGCCqGSM49BAMCA0gAMEUCIQDJ5qFXahSj9iLCs+9P
    5VixmYwTk0Fc7gD94ut3CZOzCwIgHBlh82qwBlV/8z5YgfgT+nZfKvvH5JMbMcCv
    xJhaoSc=
    -----END CERTIFICATE-----
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIGFnKsxGm8inxJHChezBSpQk430uzIOAHA8dOLhtjqazoAoGCCqGSM49
    AwEHoUQDQgAE4sMvb/TVAwv2m9CKWwxZiJYhlkKbS6TadFersoqqBGob5rmHHZfn
    XxxguvChYaUQ7a5N0GLb4QmoEkYFMJPkAg==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2021-11-25T09:56:33.563752739Z"
    init-bundle.stackrox.io/expires-at: "2022-11-25T09:57:00Z"
    init-bundle.stackrox.io/id: c09bc01d-5c2a-4df7-97c5-e3dd4bfd255a
    init-bundle.stackrox.io/name: testcluster
  creationTimestamp: null
  name: sensor-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUDqy1Lgt8MmufKg+ldH+RWjOAltQwCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM5MzY2OTk3MjcyNzY5NDg2NjYzMB4XDTIxMTEyNTA5MDgwMFoXDTI2MTEy
    NDA5MDgwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM5MzY2OTk3MjcyNzY5NDg2NjYzMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEkKu/wxEMkOJi07yovyCyJVTB+wGdyQevxZBDzeoZwjI8aM+7
    HUJ83HhnnDUZyD7nA8rqaI/GmawCwsqanckWf6NCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCAenzBYMloC7GdFoELUp2gAvU6i
    MAoGCCqGSM49BAMCA0kAMEYCIQDktvBalsuATtwHj12hQhiYfKFPmwNwRsoKQw/g
    LZaU7AIhAL+GZx/4UEgOWmaXGQe8YBELnTxM1NGqrjCSlmR7GRmw
    -----END CERTIFICATE-----
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICsjCCAligAwIBAgIIb0PrWgo8d/wwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExM5MzY2OTk3
    MjcyNzY5NDg2NjYzMB4XDTIxMTEyNTA4NTcwMFoXDTIyMTEyNTA5NTcwMFowgaUx
    LTArBgNVBAoTJGMwOWJjMDFkLTVjMmEtNGRmNy05N2M1LWUzZGQ0YmZkMjU1YTEX
    MBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7BgNVBAMMNFNFTlNPUl9TRVJWSUNF
    OiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHDAaBgNVBAUT
    EzgwMTc1MTA1MzM2MDA5MzM4ODQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS+
    l3JINI1avnDnJAKjxEK+O2A2EtOQd3OMWYzesgwvhakyGN5cnBrvMDQAxfDBinEY
    OJEGDbEY+CscG4nRwb6no4HOMIHLMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAU
    BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUKdyn
    MJCSOevOYkvoz6fIwHzjn9QwHwYDVR0jBBgwFoAUIB6fMFgyWgLsZ0WgQtSnaAC9
    TqIwTAYDVR0RBEUwQ4IPc2Vuc29yLnN0YWNrcm94ghNzZW5zb3Iuc3RhY2tyb3gu
    c3ZjghtzZW5zb3Itd2ViaG9vay5zdGFja3JveC5zdmMwCgYIKoZIzj0EAwIDSAAw
    RQIhANiUn7wv2f+/ubFEY52iOFRLDhtVPw4W9dMvqt/rFoq2AiAvESuZtDokbNLQ
    osqxgr33+rrQmDxc9GN9KHZaeLU3Ow==
    -----END CERTIFICATE-----
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIMO6fpU0h96nI5rqLyP5r9HeaJ6H8u6c16vDYLsTrc2joAoGCCqGSM49
    AwEHoUQDQgAEvpdySDSNWr5w5yQCo8RCvjtgNhLTkHdzjFmM3rIML4WpMhjeXJwa
    7zA0AMXwwYpxGDiRBg2xGPgrHBuJ0cG+pw==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2021-11-25T09:56:33.563752739Z"
    init-bundle.stackrox.io/expires-at: "2022-11-25T09:57:00Z"
    init-bundle.stackrox.io/id: c09bc01d-5c2a-4df7-97c5-e3dd4bfd255a
    init-bundle.stackrox.io/name: testcluster
  creationTimestamp: null
  name: admission-control-tls
stringData:
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICxDCCAmmgAwIBAgIJAMCF16o0x2llMAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTOTM2Njk5
    NzI3Mjc2OTQ4NjY2MzAeFw0yMTExMjUwODU3MDBaFw0yMjExMjUwOTU3MDBaMIG8
    MS0wKwYDVQQKEyRjMDliYzAxZC01YzJhLTRkZjctOTdjNS1lM2RkNGJmZDI1NWEx
    IjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0UxSDBGBgNVBAMMP0FE
    TUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAw
    LTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTM4NzI3MzEzNTMyMTQ1NzY5OTcwWTAT
    BgcqhkjOPQIBBggqhkjOPQMBBwNCAARcK4/1CUizuN/XaWLUK7absX2Lyf2nc7F8
    aqw3Gkf3aCnnFlMxwDRMkzyFyp1dyNy6TiNVMOzPe/8J8JgPhu+Fo4HHMIHEMA4G
    A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYD
    VR0TAQH/BAIwADAdBgNVHQ4EFgQUBYds/+RABDO5SrKQi0l5NG1NIr0wHwYDVR0j
    BBgwFoAUIB6fMFgyWgLsZ0WgQtSnaAC9TqIwRQYDVR0RBD4wPIIaYWRtaXNzaW9u
    LWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94LnN2
    YzAKBggqhkjOPQQDAgNJADBGAiEA1T3TPY6aGiUQ8GMEdl15tp4LSc5NqBAK40Mq
    0Qw4oSACIQDvbrVVV1gJPze6gWQu3SeJgUAheMb6CkU0YRJMYpPWwg==
    -----END CERTIFICATE-----
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIAS8F/SBeOPX4jpj/l3FB80SyFpdjDK4rUTxIV02tcr6oAoGCCqGSM49
    AwEHoUQDQgAEXCuP9QlIs7jf12li1Cu2m7F9i8n9p3OxfGqsNxpH92gp5xZTMcA0
    TJM8hcqdXcjcuk4jVTDsz3v/CfCYD4bvhQ==
    -----END EC PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUDqy1Lgt8MmufKg+ldH+RWjOAltQwCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM5MzY2OTk3MjcyNzY5NDg2NjYzMB4XDTIxMTEyNTA5MDgwMFoXDTI2MTEy
    NDA5MDgwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM5MzY2OTk3MjcyNzY5NDg2NjYzMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEkKu/wxEMkOJi07yovyCyJVTB+wGdyQevxZBDzeoZwjI8aM+7
    HUJ83HhnnDUZyD7nA8rqaI/GmawCwsqanckWf6NCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCAenzBYMloC7GdFoELUp2gAvU6i
    MAoGCCqGSM49BAMCA0kAMEYCIQDktvBalsuATtwHj12hQhiYfKFPmwNwRsoKQw/g
    LZaU7AIhAL+GZx/4UEgOWmaXGQe8YBELnTxM1NGqrjCSlmR7GRmw
    -----END CERTIFICATE-----
